services:
  redis:
    image: redis:alpine
    networks:
      - test-net

  backend:
    image: cache-test:latest
    ports:
      - "8080:8080"
    networks:
      - test-net

networks:
  test-net:
    driver: bridge